# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcatslist', '0002_auto_20160623_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('item', 'Item'), ('service', 'Service')], max_length=20)),
                ('location', models.CharField(choices=[('greenville', 'Greenville'), ('charleston', 'Charleston'), ('ashville', 'Asheville'), ('atlanta', 'Atlanta')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
