# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcatslist', '0003_offerpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('item', 'Item'), ('service', 'Service')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='offerpost',
            name='catnip',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='offerpost',
            name='catsitting',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='offerpost',
            name='cleaning',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='offerpost',
            name='cooking',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='offerpost',
            name='food',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='offerpost',
            name='furniture',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='offerpost',
            name='toys',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userdescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offerpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcatslist.CategoryList'),
        ),
    ]
