# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcatslist', '0005_auto_20160624_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='offerpost',
            name='catnip',
        ),
        migrations.RemoveField(
            model_name='offerpost',
            name='catsitting',
        ),
        migrations.RemoveField(
            model_name='offerpost',
            name='cleaning',
        ),
        migrations.RemoveField(
            model_name='offerpost',
            name='cooking',
        ),
        migrations.RemoveField(
            model_name='offerpost',
            name='food',
        ),
        migrations.RemoveField(
            model_name='offerpost',
            name='furniture',
        ),
        migrations.RemoveField(
            model_name='offerpost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='offerpost',
            name='toys',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile photo',
        ),
        migrations.AddField(
            model_name='offerpost',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='appcatslist.City'),
            preserve_default=False,
        ),
    ]
