# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcatslist', '0008_auto_20160625_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
    ]
