# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcatslist', '0009_userprofile_profile photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile photo',
            new_name='photo',
        ),
    ]
