# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcatslist', '0010_auto_20160625_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerpost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photos'),
        ),
    ]
