# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 09:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appcatslist', '0011_offerpost_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 26, 9, 16, 38, 404417, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
